
export const GET_ALL_SUBTASK_REQUEST = "GET_ALL_SUBTASK_REQUEST";
export const ADD_SUBTASK_REQUEST = "ADD_SUBTASK_REQUEST";
export const UPDATE_SUBTASK_REQUEST = "UPDATE_SUBTASK_REQUEST";

export const GET_ALL_SUBTASK_SUCCESS = "GET_ALL_SUBTASK_SUCCESS";
export const ADD_SUBTASK_SUCCESS = "ADD_SUBTASK_SUCCESS";
export const UPDATE_SUBTASK_SUCCESS = "UPDATE_SUBTASK_SUCCESS";


export const GET_ALL_SUBTASK_ERROR = "GET_ALL_SUBTASK_ERROR";
export const ADD_SUBTASK_ERROR = "ADD_SUBTASK_ERROR";
export const UPDATE_SUBTASK_ERROR = "UPDATE_SUBTASK_ERROR";
