
export const GET_ALL_TODO_REQUEST = "GET_ALL_TODO_REQUEST";
export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";

export const GET_ALL_TODO_SUCCESS = "GET_ALL_TODO_SUCCESS";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";


export const GET_ALL_TODO_ERROR = "GET_ALL_TODO_ERROR";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";
export const UPDATE_TODO_ERROR = "UPDATE_TODO_ERROR";
